---

- name: Create student VMs in Azure
  hosts: localhost
  connection: local

  tasks:
    - name: Create the virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: dk8s_training_vnet
        address_prefixes: "10.0.0.0/16"
        tags: "{{ object_tags }}"

    - name: Create the subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: dk8s_training_subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: dk8s_training_vnet

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: dk8s_training_sec_group
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
        tags: "{{ object_tags }}"

    # for each VM that needs to be created
    - name: Create Public IP addresses
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "dk8s_training_pubip_{{ item }}"
        tags: "{{ object_tags }}"
      register: output_ip_address
      loop: "{{ students }}"

    - name: SSH connection strings
      debug:
        msg: "ssh {{item}}@{{ output_ip_address.results | selectattr('item', 'equalto', item) | map(attribute='state') | list | map(attribute='ip_address') | list | first }}"
      loop: "{{ students }}"

    - name: Create virtual interface cards
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "dk8s_training_NIC_{{item}}"
        virtual_network: dk8s_training_vnet
        subnet: dk8s_training_subnet
        public_ip_name: "dk8s_training_pubip_{{ item }}"
        security_group: dk8s_training_sec_group
        tags: "{{ object_tags }}"
      loop: "{{ students }}"

    - name: Create VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "dk8sTrainingVM4{{item}}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ item }}"
        admin_password: "{{ master_password }}"
        ssh_password_enabled: true
        network_interfaces: "dk8s_training_NIC_{{item}}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
          tags: "{{ object_tags }}"
      loop: "{{ students }}"

    - name: Add the new VMs to the Ansible group
      add_host:
        hostname: "{{ output_ip_address.results | selectattr('item', 'equalto', item) | map(attribute='state') | list | map(attribute='ip_address') | list | first }}"
        groups: created
        ansible_ssh_user: "{{ item }}"
        ansible_ssh_pass: "{{ master_password }}"
      loop: "{{ students }}"

#########################
- name: Configure software on the created VMs
  hosts: created
  gather_facts: False
  become: True

  tasks:
    - name: Update everything
      apt:
        upgrade: True
        update_cache: True

    - name: Add Docker repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Install K8S
      snap:
        name: microk8s
        state: present
        classic: True

    - name: Install kubectl
      lineinfile:
          dest: "/home/{{ ansible_ssh_user }}/.bash_aliases"
          create: True
          mode: 0644
          line: "alias kubectl='microk8s.kubectl'"
          regexp: "^alias kubectl="

    - name: Add user to docker & microk8s groups
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker,microk8s
        append: True

    - name: Enable microk8s add-ons
      shell: microk8s.enable dns dashboard